// Generated by CoffeeScript 1.8.0
var arity5;

module.exports = arity5 = function(fn, n) {
  if (!(n > 0)) {
    n = 0;
  }
  if (n === 0) {
    return function() {
      return fn.call(this);
    };
  } else if (n === 1) {
    return function(a) {
      return fn.apply(this, arguments);
    };
  } else if (n === 2) {
    return function(a, b) {
      return fn.apply(this, arguments);
    };
  } else if (n === 3) {
    return function(a, b, c) {
      return fn.apply(this, arguments);
    };
  } else if (n === 4) {
    return function(a, b, c, d) {
      return fn.apply(this, arguments);
    };
  } else if (n === 5) {
    return function(a, b, c, d, e) {
      return fn.apply(this, arguments);
    };
  } else {
    throw new RangeError("Function must take 5 or fewer arguments");
  }
};
