// Generated by CoffeeScript 1.8.0
var arity, copy;

arity = require("./arity");

module.exports = copy = function(fn) {
  var func;
  func = function() {
    return fn.apply(this, arguments);
  };
  return arity(func, fn.length);
};
