// Generated by CoffeeScript 1.8.0
var arity, curry;

arity = require("./arity");

module.exports = curry = function(fn) {
  var arg, curried, i, len, outer, _i, _len;
  len = arguments.length - 1;
  outer = new Array(len);
  for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
    arg = arguments[i];
    if (i > 0) {
      outer[i - 1] = arg;
    }
  }
  curried = function() {
    var args, j, outerArg, outerLen, _j, _k, _len1, _len2;
    outerLen = outer.length;
    len = arguments.length + outerLen;
    args = new Array(len);
    for (i = _j = 0, _len1 = outer.length; _j < _len1; i = ++_j) {
      outerArg = outer[i];
      args[i] = outerArg;
    }
    for (j = _k = 0, _len2 = arguments.length; _k < _len2; j = ++_k) {
      arg = arguments[j];
      args[outerLen + j] = arg;
    }
    if (args.length >= fn.length) {
      return fn.apply(this, args);
    } else {
      return curry.apply(null, [fn].concat(args));
    }
  };
  return arity(curried, fn.length - len);
};
