// Generated by CoffeeScript 1.8.0
var arity, demethodize;

arity = require("./arity");

module.exports = demethodize = function(fn, newArity) {
  var func;
  func = function(context) {
    var arg, args, i, _i, _len;
    args = new Array(arguments.length - 1);
    for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
      arg = arguments[i];
      if (i > 0) {
        args[i - 1] = arg;
      }
    }
    return fn.apply(context, args);
  };
  return arity(func, newArity || fn.length + 1);
};
