// Generated by CoffeeScript 1.8.0
(function() {
  var firstToLast, rotate;

  rotate = require("./rotate");

  module.exports = firstToLast = function(fn) {
    return rotate(fn, 1);
  };

}).call(this);
