// Generated by CoffeeScript 1.8.0
var decorate, extend, funcs, methods;

extend = function(target, source) {
  var key;
  for (key in source) {
    target[key] = source[key];
  }
  return target;
};

module.exports = decorate = function(fn) {
  return extend(fn, methods);
};

methods = {};

funcs = {
  curry: require("./curry"),
  arity: require("./arity"),
  nAry: require("./n-ary"),
  unary: require("./unary"),
  binary: require("./binary"),
  swap: require("./swap"),
  flip: require("./flip"),
  reverse: require("./reverse"),
  partial: require("./partial"),
  partialConstructor: require("./partial-constructor"),
  rotate: require("./rotate"),
  firstToLast: require("./first-to-last"),
  lastToFirst: require("./last-to-first"),
  demethodize: require("./demethodize"),
  copy: require("./copy")
};

Object.keys(funcs).forEach(function(key) {
  return methods[key] = decorate(function() {
    var arg, args, i, ret, _i, _len;
    args = new Array(arguments.length + 1);
    args[0] = this;
    for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
      arg = arguments[i];
      args[i + 1] = arg;
    }
    ret = funcs[key].apply(null, args);
    if (typeof ret === "function") {
      return decorate(ret);
    } else {
      return ret;
    }
  });
});

extend(decorate, funcs);
