// Generated by CoffeeScript 1.8.0
var arity, reverse;

arity = require("./arity");

module.exports = reverse = function(fn) {
  var func;
  func = function() {
    var arg, args, i, len, _i;
    len = arguments.length;
    args = new Array(len);
    for (i = _i = arguments.length - 1; _i >= 0; i = _i += -1) {
      arg = arguments[i];
      args[len - i - 1] = arg;
    }
    return fn.apply(this, args);
  };
  return arity(func, fn.length);
};
