// Generated by CoffeeScript 1.8.0
var arity, swap;

arity = require("./arity");

module.exports = swap = function(fn, p1, p2) {
  var func;
  func = function() {
    var a, arg, args, b, i, _i, _len;
    args = new Array(arguments.length);
    for (i = _i = 0, _len = arguments.length; _i < _len; i = ++_i) {
      arg = arguments[i];
      args[i] = arg;
    }
    a = args[p1];
    b = args[p2];
    args[p2] = a;
    args[p1] = b;
    return fn.apply(this, args);
  };
  return arity(func, fn.length);
};
