// Generated by CoffeeScript 1.8.0
(function() {
  var arity, swap;

  arity = require("./arity");

  module.exports = swap = function(fn, p1, p2) {
    var func;
    func = function() {
      var arg, args, temp, _i, _len;
      args = new Array(arguments.length);
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        arg = arguments[_i];
        args[i] = arg;
      }
      temp = args[p1];
      args[p1] = args[p2];
      args[p2] = temp;
      return fn.apply(this, args);
    };
    return arity(func, fn.length);
  };

}).call(this);
