module.exports =
  curry: require "./curry"
  arity: require "./arity"
  nAry: require "./n-ary"
  unary: require "./unary"
  binary: require "./binary"
  swap: require "./swap"
  flip: require "./flip"
  reverse: require "./reverse"
  partial: require "./partial"
  partialConstructor: require "./partial-constructor"
  rotate: require "./rotate"
  firstToLast: require "./first-to-last"
  lastToFirst: require "./last-to-first"
  demethodize: require "./demethodize"
