module.exports =
  curry: require "./curry.coffee"
  arity: require "./arity.coffee"
  nAry: require "./n-ary.coffee"
  unary: require "./unary.coffee"
  binary: require "./binary.coffee"
  swap: require "./swap.coffee"
  flip: require "./flip.coffee"
  reverse: require "./reverse.coffee"
  partial: require "./partial.coffee"
  partialConstructor: require "./partialConstructor"
  rotate: require "./rotate.coffee"
  firstToLast: require "./firstToLast.coffee"
  lastToFirst: require "./lastToFirst.coffee"
  demethodize: require "./demethodize.coffee"
